# Generated by Django 4.0.4 on 2022-06-02 08:52

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.IntegerField()),
                ('Description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=250)),
                ('CP', models.CharField(max_length=250)),
                ('Price', models.FloatField()),
                ('Rooms', models.IntegerField()),
                ('Baths', models.IntegerField()),
                ('is_sold', models.BooleanField(default=False)),
                ('house_image', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to)),
                ('location', models.CharField(max_length=450, null=True)),
                ('IdCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city')),
                ('IdState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='IdState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.state'),
        ),
    ]
