version: '3.1'
services:
  backend:
    container_name: web_development_uadec_backend
    restart: on-failure:10
    build:
      context: backend/.
    volumes:
      - ./backend:/backend
    command: >
      sh -c "python manage.py makemigrations api &&
             python manage.py migrate api &&
             python manage.py runserver 0.0.0.0:5000"
    ports:
      - "5000:5000"
    depends_on:
      - database
    links:
      - database
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  database:
    container_name: web_development_uadec_database
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  database_manager:
    container_name: web_development_uadec_database_manager
    restart: on-failure:10
    image: phpmyadmin/phpmyadmin:5.1.1
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=database
      - PMA_ARBITRARY=1
    depends_on:
      - database
    links:
      - database

